openapi: 3.0.0
info:
  title: 'Laravel Swagger Base Project'
  description: 'Documentação da API do meu aplicativo'
  version: 1.0.0
paths:
  /auth/register:
    post:
      tags:
        - 'Auth Management'
      summary: 'Registro de usuário.'
      description: 'Registro necessário para consumo de nossos serviços'
      operationId: ed42f392010c301892e640067141676e
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required:
                - name
                - email
                - password
                - c_password
              properties:
                name:
                  type: string
                email:
                  type: string
                  format: email
                password:
                  type: string
                c_password:
                  type: string
              type: object
      responses:
        '200':
          description: 'User register successfully.'
        '400':
          description: 'Validation Error.'
        '500':
          description: 'Internal Server Error.'
  /auth/login:
    post:
      tags:
        - 'Auth Management'
      summary: 'Login de usuário'
      description: 'Autenticação necessária para consumo de nossos serviços'
      operationId: 8cb7742ae98d0990acb2907c4e00bf24
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
              type: object
      responses:
        '200':
          description: 'User login successfully.'
        '401':
          description: Unauthorized.
        '500':
          description: 'Internal Server Error.'
  /auth/me:
    get:
      tags:
        - 'Auth Management'
      summary: 'Obter o usuário autenticado atual'
      operationId: a9c495788506b114956e3f509e5d90a2
      responses:
        '200':
          description: 'Usuário recuperado com sucesso'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: 'Não autenticado'
components:
  schemas:
    User:
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: 'João Vitor Felipe'
        email:
          type: string
          example: jvitorfr@outlook.com
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      type: object
  securitySchemes:
    bearerAuth:
      type: http
      bearerFormat: JWT
      scheme: bearer
tags:
  -
    name: 'Auth Management'
    description: 'APIs relacionadas à autenticação de usuários'
