openapi: 3.0.0
info:
  title: 'Test Context'
  description: 'Documentação da API do meu aplicativo'
  version: 1.0.0
paths:
  /register:
    post:
      summary: 'Registro de usuário'
      description: 'Registro necessária para consumo de nossos serviços'
      operationId: 7169e2b01b06d3afa594a11ab6422148
      responses:
        '200':
          description: 'User register successfully.'
  /login:
    get:
      summary: 'Login de usuário'
      description: 'autenticação necessária para consumo de nossos serviços'
      operationId: 1801e25f84de2ebe1b75b549ded1f08b
      responses:
        '200':
          description: 'User login successfully.'
  /test:
    get:
      summary: 'mostra pros curiosos que o bagulho funciona'
      description: 'Retorna os dados em formato JSON.'
      operationId: 7e4cbd87f862955499cc9fb93a25b372
      responses:
        '200':
          description: 'Dados retornados com sucesso'
  /test-pre-commit:
    get:
      summary: 'está funcionando o pre commit'
      description: 'Retorna os dados em formato JSON.'
      operationId: 6132ec222c5d6ad71f66ad2f583a1ffd
      responses:
        '200':
          description: 'Dados retornados com sucesso'
