openapi: 3.0.0
info:
  title: 'Test Context'
  description: 'Documentação da API do meu aplicativo'
  version: 1.0.0
paths:
  /test:
    get:
      summary: 'mostra pros curiosos que o bagulho funciona'
      description: 'Retorna os dados em formato JSON.'
      operationId: 7e4cbd87f862955499cc9fb93a25b372
      responses:
        '200':
          description: 'Dados retornados com sucesso'
  /test-pre-commit:
    get:
      summary: 'está funcionando o pre commit'
      description: 'Retorna os dados em formato JSON.'
      operationId: 6132ec222c5d6ad71f66ad2f583a1ffd
      responses:
        '200':
          description: 'Dados retornados com sucesso'
  /api/login:
    post:
      summary: 'Login de usuário'
      description: 'Autenticação necessária para consumo de nossos serviços'
      operationId: a3b306d14572d1f4bd6c064b3233e7b8
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
              type: object
      responses:
        '200':
          description: 'User login successfully.'
        '401':
          description: Unauthorised.
